### ISSUE TITLE
not working in qlik sense latest 1.1.0 build 31

### ISSUE THREAD

**Issue by yoavpip** [yblake/deltaViz#5]
hi 
i have been using this amazing extension with qliksense.
once upgraded to latest qlik version (1.1.0 build 31) and downloaded your latest update - 
i cant use it 
i get this massage : 
'Invalid Visualization, the visualization was not found in server'

i was a lot of extension and none did me any problem when upgrading .

have any idea how to solve ?
thanks

**Comment by yblake** [comment]
I'm unable to reproduce.

We just upgraded Sense server this morning and it works well. We just had to delete existing extension prior to import it again.

If your issue is about Sense Desktop, it may be a cache issue as discussed in Branch, you may need to clean Desktop Cache using dev tools settings. I use this to clean Sense Desktop cache :
 
In Qlik Sense Desktop, Open your application, then activate Chrome Dev tools by pressing CTRL+SHIFT+Right click, then select "Show Dev tools" menu item.
 
In Chrom Dev Tools tab, click on Settings icon (up right the screen) and set first option on :
"Disable cache (while DevTools is open)". Then close Dev tools settings.
 
Go back to your application Tab, and refresh your application display using CTRL+F5.

Regards

**Comment by yoavpip** [comment]
Solved !
Thanks for the assistance



?-17 ???? 2015, ???? 13:55, "Yves BLAKE" <notifications@github.com<mailto:notifications@github.com>> ???/?:


I'm unable to reproduce.

We just upgraded Sense server this morning and it works well. We just had to delete existing extension prior to import it again.

If your issue is about Sense Desktop, it may be a cache issue as discussed in Branch, you may need to clean Desktop Cache using dev tools settings. I use this to clean Sense Desktop cache :

In Qlik Sense Desktop, Open your application, then activate Chrome Dev tools by pressing CTRL+SHIFT+Right click, then select "Show Dev tools" menu item.

In Chrom Dev Tools tab, click on Settings icon (up right the screen) and set first option on :
"Disable cache (while DevTools is open)". Then close Dev tools settings.

Go back to your application Tab, and refresh your application display using CTRL+F5.

Regards

-
