### ISSUE TITLE
Issue with NULL-Values

### ISSUE THREAD

**Issue by MSRobert** [yblake/deltaViz#8]
Yves,

this is a great extension that we have been using quite extensively throughout our project. We have, however, found a bug which makes it hard to rely on the presented data.

Following scenario:
Dimension is fixed to ='My KPI'
1st KPI is sum(revenue) / count(countries)
2nd KPI is sum(last_year_revenue) / count(countries)

now, if count(countries) is 0 then the KPIs will be Null. Normally the Extension doesn't display anything in that case. However, if count(countries) has been anything but 0 and due to a selection becomes 0 then the extension displays the previous value and does not disappear. 

I could reproduce this issue on different installations (server and desktop client), where the latest tested version is Qlik Sense Desktop June 2017

Could you please have a look at that?

Cheers
Robert

**Comment by yblake** [comment]
We do not really check for null values in expressions results.

I cannot reproduce without your data, but the way to go would be to handle null value as zero's in datapage matrix mapping, replacing _d[measure_actual].qNum_ by _(d[measure_actual].qIsNull ? 0 : d[measure_actual].qNum)_.  Same for _d[measure_previous].qNum_ 

Zero values are handled later in the extension, in fact such cells are simply destroyed by a dataD3.splice instruction, as we can't compute any deviation if previous or actual value is 0.

Another (and may be wizer) solution would be to filter the qMatrix prior to map his content into dataD3.

If you don't want to put hands in code, you could change your expression in : _if (count(countries) > 0, sum(revenue) / count(countries) ,0)_ and _if (count(countries) > 0, sum(last_year_revenue) / count(countries) ,0)_ 

If you need further assistance, please provide sample data.
Regards

**Comment by MSRobert** [comment]
Thank you! I changed the lines in the extension and now it works as expected! 

Regarding the example; You could just use this data to test your extension:

Countries:
load * Inline [
CC, Country
DE, Germany
US, United States
GB, England
];

Revenue:
load * inline [
year, CC, revenue
2016, DE, 123456
2016, US, 234567
2016, GB, 345678
2016, A, 4567
2017, DE, 234567
2017, US, 345678
2017, GB, 456789
2017, A, 5678];

Now, if you filter your data by CC=A, then count(Country) will be 0 and the division by 0 will be null. 

Best Regards
Robert

**Comment by yblake** [comment]
Hi, thanks again for using the extension, and thanks also for providing sample data.

With this data, the console shows a bug is caused by null values generating NaN (Not a Number) values in internal summarizations (sumActual and/or sumPrevious) results, thus the extension doesn't repaint itself.

You can filter theses null values by adding a filter in the code :
`var dataD3 = layout.qHyperCube.qDataPages[page].qMatrix.filter( 
	(d) => !d[measure_actual].qIsNull && !d[measure_previous].qIsNull
).map( function(d) {`


I'll implement this fix in next release.

However in your sample data case this is not a formal "null" value problem, but a "missing" value due to incorrect data model  integrity (you have a missing Country name).

I recommend to handle this particular case in either following ways :

First a quick (and dirty) solution : Change  _sum(revenue) / count(countries)_ to  _sum(revenue) / count(distinct CC)_ so that you get the correct average deviation when selecting CC value "A". Do same for _last_year_revenue_.  

This is "dirty" because you have to do this for all formulas in the App to get consistent results. Also a side effect is that for large data tables, the distinct clause will takes longer to compute as it cannot be efficiently parallelized. 

This is why I would prefer a second way, which is to avoid data integrity "holes" in your model. For example, add following instructions in your script :

`Concatenate (Countries) Load Distinct
	CC,
    '<Unknown country ' & CC & '>' as Country
Resident
	Revenue
Where
	IsNull(Lookup('Country','CC',CC,'Countries'))
;`

Now you'll have a visible `<Unknown country A>` country name instead of missing value, that will last until somebody corrects the country table. From experience, this will save you days (weeks...) when some end user will ask you why your result is different from his old XL report...
